Remove sourceMappingURL comment from bootstrap.min.css
I am seeing recurring errors in production logs/Sentry:

FileNotFoundError: [Errno 2] No such file or directory: '.../site-packages/st_clickable_images/frontend/build/bootstrap.min.css.map'

It looks like `bootstrap.min.css` includes:

/*# sourceMappingURL=bootstrap.min.css.map */

but `bootstrap.min.css.map` is not included in the distributed package.

Because of this, the browser requests the map file, and Streamlit logs a read error (404) repeatedly.

So I removed the `sourceMappingURL` comment from `bootstrap.min.css` before publishing